scan_filter_chain:

- name: Remove over 0.35 meters on the right
  type: laser_filters/LaserScanBoxFilter
  params:
    box_frame: lidar_link
    min_x: -0.47
    max_x: 0.47
    min_y: -0.34
    max_y: 0.34
    min_z: -0.1
    max_z: 0.1